<#
.SYNOPSIS
    One-time Cloudflare setup for Rydius Stream: public tunnel + TURN key.

.DESCRIPTION
    Run this once from this folder in PowerShell. It:
      1. Authorizes cloudflared against the rydius.in zone (one browser step).
      2. Creates the named tunnel "rydius-stream" (reused on later runs).
      3. Writes cloudflared_config.yml pointing stream.rydius.in at port 3000.
      4. Creates the DNS record stream.rydius.in -> the tunnel.
      5. Asks for a Cloudflare TURN key + API token and writes secrets.local.env.

    After this, start_host.bat starts the tunnel automatically on every run.
#>
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $PSCommandPath
$cloudflared = Join-Path $scriptDir 'cloudflared_win\cloudflared.exe'
$tunnelName = 'rydius-stream'
$hostname = 'stream.rydius.in'
$zone = 'rydius.in'
$tunnelConfigPath = Join-Path $scriptDir 'cloudflared_config.yml'
$secretsPath = Join-Path $scriptDir 'secrets.local.env'
$cfDir = Join-Path $env:USERPROFILE '.cloudflared'
$certPath = Join-Path $cfDir 'cert.pem'

if (-not (Test-Path -LiteralPath $cloudflared -PathType Leaf)) {
    $cloudflaredDir = Split-Path -Parent $cloudflared
    New-Item -ItemType Directory -Path $cloudflaredDir -Force | Out-Null
    $downloadUrl = 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe'
    Write-Host 'Downloading the official Cloudflare Tunnel client for Windows...' -ForegroundColor Cyan
    Invoke-WebRequest -Uri $downloadUrl -OutFile $cloudflared -UseBasicParsing
    if (-not (Test-Path -LiteralPath $cloudflared -PathType Leaf) -or (Get-Item -LiteralPath $cloudflared).Length -lt 1MB) {
        throw "cloudflared.exe download did not produce a valid file: $cloudflared"
    }
    Write-Host "Downloaded cloudflared.exe to $cloudflared" -ForegroundColor Green
}

# 1. One-time browser authorization ---------------------------------------
if (-not (Test-Path -LiteralPath $certPath -PathType Leaf)) {
    Write-Host "One browser step: authorize cloudflared for $zone." -ForegroundColor Cyan
    Write-Host 'A URL will be printed below - open it, select the zone, click Allow,' -ForegroundColor Cyan
    Write-Host 'then come back here. This script waits for you to finish.' -ForegroundColor Cyan
    & $cloudflared tunnel login
    if ($LASTEXITCODE -ne 0) { throw 'cloudflared tunnel login failed.' }
    Write-Host 'Authorization received.' -ForegroundColor Green
} else {
    Write-Host 'cloudflared is already authorized (cert.pem found).' -ForegroundColor Cyan
}

# 2. Named tunnel ----------------------------------------------------------
function Get-TunnelId([string]$Name) {
    $listing = & $cloudflared tunnel list --output json 2>$null | ConvertFrom-Json
    $match = @($listing) | Where-Object { $_.name -eq $Name } | Select-Object -First 1
    if ($match) { return $match.id }
    return $null
}

$tunnelId = Get-TunnelId $tunnelName
if ($tunnelId) {
    Write-Host "Reusing tunnel '$tunnelName' ($tunnelId)." -ForegroundColor Cyan
} else {
    Write-Host "Creating tunnel '$tunnelName'..." -ForegroundColor Cyan
    & $cloudflared tunnel create $tunnelName
    if ($LASTEXITCODE -ne 0) { throw 'cloudflared tunnel create failed.' }
    $tunnelId = Get-TunnelId $tunnelName
    if (-not $tunnelId) { throw "Tunnel '$tunnelName' was created but does not appear in tunnel list." }
    Write-Host "Created tunnel $tunnelName ($tunnelId)." -ForegroundColor Green
}

$credentialsFile = Join-Path $cfDir "$tunnelId.json"
if (-not (Test-Path -LiteralPath $credentialsFile -PathType Leaf)) {
    throw "Tunnel credentials file not found: $credentialsFile"
}

# 3. Tunnel config ---------------------------------------------------------
$configLines = @(
    '###############################################'
    '# Cloudflare tunnel for Rydius Stream.'
    '# Generated by setup_cloudflared.ps1 - rerun that script instead of editing.'
    '# The tunnel carries HTTP only (page + WHEP signaling); video UDP for remote'
    '# viewers relays through Cloudflare TURN (secrets.local.env -> /stream-api/turn).'
    '###############################################'
    "tunnel: $tunnelId"
    "credentials-file: $credentialsFile"
    ''
    'ingress:'
    "  - hostname: $hostname"
    '    service: http://127.0.0.1:3000'
    '  - service: http_status:404'
)
Set-Content -LiteralPath $tunnelConfigPath -Value $configLines -Encoding UTF8
Write-Host "Wrote $tunnelConfigPath" -ForegroundColor Green

# 4. DNS -------------------------------------------------------------------
Write-Host "Ensuring $hostname points at the tunnel..." -ForegroundColor Cyan
& $cloudflared tunnel route dns $tunnelName $hostname
if ($LASTEXITCODE -ne 0) {
    Write-Warning "DNS route command reported an error. If $hostname already exists in Cloudflare DNS this is fine; otherwise rerun this script."
}

# 5. TURN key --------------------------------------------------------------
Write-Host ''
Write-Host 'Cloudflare TURN key (optional):' -ForegroundColor Cyan
Write-Host "  Dashboard: $zone -> Realtime -> TURN -> Create TURN key" -ForegroundColor Cyan
Write-Host '  Docs:      https://developers.cloudflare.com/realtime/turn/generate-credentials/' -ForegroundColor Cyan
Write-Host '  NOTE: TURN is a metered Cloudflare product - the dashboard may ask for a' -ForegroundColor Yellow
Write-Host '  payment method even though the first 1,000 GB/month is free. Without it,' -ForegroundColor Yellow
Write-Host '  viewers still connect through the free Cloudflare STUN punch-through path.' -ForegroundColor Yellow
Write-Host '  Press Enter to skip - TURN can be enabled later by rerunning this script.'
$keyId = Read-Host 'TURN key ID'
if ($keyId -and $keyId.Trim()) {
    $apiToken = Read-Host 'TURN API token (copy it while the dashboard still shows it)'
    $secretsLines = @(
        '# Cloudflare TURN credentials for server-side credential minting.'
        '# Written by setup_cloudflared.ps1. Keep this file private: browsers'
        '# only ever receive short-lived credentials minted by server.js.'
        "CF_TURN_KEY_ID=$($keyId.Trim())"
        "CF_TURN_KEY_TOKEN=$($apiToken.Trim())"
    )
    Set-Content -LiteralPath $secretsPath -Value $secretsLines -Encoding UTF8
    Write-Host "Wrote $secretsPath" -ForegroundColor Green
} else {
    Write-Warning 'TURN key skipped: viewers will rely on the free STUN punch-through path (works for most home networks; a viewer behind a strict NAT may fail).'
}

Write-Host ''
Write-Host 'Setup complete.' -ForegroundColor Green
Write-Host "  Page:     https://$hostname  (once start_host.bat is running)"
Write-Host '  Fallback: Tailscale Serve URL (see README)'
